variables:
  TAG_IMAGE_FRONT: $CI_REGISTRY_IMAGE_FRONT:latest
stages:
  - make_docker_image
  - deploy

.before script docker registry login: &before-script-docker-registry-login
  - mkdir ~/.docker
  - cat $CR_CONFIG > ~/.docker/config.json


make_front_docker_image:
  stage: make_docker_image
  image: docker:latest
  before_script:
    - *before-script-docker-registry-login
  script:
    - cd frontend
    - docker build --pull -t $TAG_IMAGE_FRONT -f ./Dockerfile .
    - docker push $TAG_IMAGE_FRONT
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual

deploy:
  stage: deploy
  image: hub.66bit.ru/shared/stk8s:1.26.2
  script:
    - kubectl delete -f ./cicd/kubernetes-deployment.yaml
    - kubectl apply -f ./cicd/kubernetes-deployment.yaml
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual
